# .air.toml

# Command build & run
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"

# Watch directories
include_dir = ["."]
exclude_dir = ["tmp", "vendor", "node_modules", ".idea", "logs"]

# File patterns
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_file = []

# Logs
log_color = true
log_time = true

# Misc
stop_on_error = true