// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ListUsersRequest struct {
	ID     *string `json:"id,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
}

type LoginResponse struct {
	User        *User  `json:"user"`
	AccessToken string `json:"access_token"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	Password    string  `json:"password"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	LastName    *string `json:"last_name,omitempty"`
	FirstName   *string `json:"first_name,omitempty"`
	UseYn       *int    `json:"use_yn,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	CreatedBy   *string `json:"created_by,omitempty"`
	UpdatedBy   *string `json:"updated_by,omitempty"`
	VerifyCode  *string `json:"verify_code,omitempty"`
}

type UserInput struct {
	Username    string  `json:"username"`
	Password    string  `json:"password"`
	Email       string  `json:"email"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	LastName    *string `json:"last_name,omitempty"`
	FirstName   *string `json:"first_name,omitempty"`
}

type UserUpdateInput struct {
	Email       string  `json:"email"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	LastName    *string `json:"last_name,omitempty"`
	FirstName   *string `json:"first_name,omitempty"`
}
