// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ListUsersRequest struct {
	ID     *string `json:"id,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	Password    string  `json:"password"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	LastName    *string `json:"last_name,omitempty"`
	FirstName   *string `json:"first_name,omitempty"`
	UseYn       string  `json:"use_yn"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	CreatedUser *string `json:"created_user,omitempty"`
	UpdatedUser *string `json:"updated_user,omitempty"`
}

type UserInput struct {
	Username    string  `json:"username"`
	Password    string  `json:"password"`
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	LastName    *string `json:"last_name,omitempty"`
	FirstName   *string `json:"first_name,omitempty"`
	UseYn       *string `json:"use_yn,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	CreatedUser *string `json:"created_user,omitempty"`
	UpdatedUser *string `json:"updated_user,omitempty"`
}
