package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"tsv-golang/internal/graph/model"
)

// CreateBoard is the resolver for the createBoard field.
func (r *mutationResolver) CreateBoard(ctx context.Context, input *model.BoardInput) (*model.Board, error) {
	userLogin := ctx.Value("userLogin").(string)
	return r.Service.BoardService.CreateBoard(userLogin, input)
}

// UpdateBoard is the resolver for the updateBoard field.
func (r *mutationResolver) UpdateBoard(ctx context.Context, id string, input *model.BoardUpdateInput) (*model.Board, error) {
	panic(fmt.Errorf("not implemented: UpdateBoard - updateBoard"))
}

// DeleteBoard is the resolver for the deleteBoard field.
func (r *mutationResolver) DeleteBoard(ctx context.Context, id string) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteBoard - deleteBoard"))
}

// ListBoard is the resolver for the listBoard field.
func (r *queryResolver) ListBoard(ctx context.Context, request *model.ListBoardRequest) ([]*model.Board, error) {
	panic(fmt.Errorf("not implemented: ListBoard - listBoard"))
}

// GetBoardByID is the resolver for the getBoardById field.
func (r *queryResolver) GetBoardByID(ctx context.Context, id string) (*model.Board, error) {
	panic(fmt.Errorf("not implemented: GetBoardByID - getBoardById"))
}
